name: "Tiny Forward Proxy"
version: "1.1.1"
slug: "tiny_forward_proxy"
description: "Lightweight HTTP/HTTPS Forward Proxy to route traffic through your Home IP"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
options:
  auth_user: "dev_user"        # Thay bằng username của bạn
  auth_pass: "Password123_S3cur3" # Thay bằng pass cực khó (Lưu ý: KHÔNG dùng ký tự @)
  log_level: "Info"
schema:
  auth_user: str
  auth_pass: str
  log_level: list(Info|Connect|Notice|Warning|Error|Critical)
ports:
  8888/tcp: 8888
